(function(){
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}

  /* V3 print: keep the print page, but trigger the browser print dialog after it has rendered. */
  function printV3(){
    var data=(function(){var a=Array.isArray(window.adminMembers)?window.adminMembers.slice():[];var q=(document.getElementById('adminQ')&&document.getElementById('adminQ').value||'').toLowerCase();a=a.filter(function(m){return [m.full_name,m.preferred_name,m.mobile,m.whatsapp_phone,m.email,m.current_city,m.current_state,m.current_country,m.profession,m.company].some(function(v){return String(v||'').toLowerCase().includes(q);});});var f=window.adminFilter||'all';if(f==='complete')a=a.filter(function(m){return m.profile_completed;});if(f==='pending')a=a.filter(function(m){return !m.profile_completed;});if(f==='admins')a=a.filter(function(m){return (window.adminRoles||{})[m.id]==='admin';});return a;})();
    var rows=data.map(function(m,i){return '<tr><td>'+(i+1)+'</td><td>'+esc(m.full_name||m.preferred_name||'')+'</td><td>'+esc(m.detailed_address||'')+'</td><td>'+esc(m.current_city||'')+'</td><td>'+esc(m.mobile||m.whatsapp_phone||'')+'</td><td>'+esc(m.email||'')+'</td></tr>';}).join('');
    var w=window.open('','_blank','width=1200,height=800');
    if(!w){alert('Please allow pop-ups for this site to print the list.');return;}
    w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>COEP ENTC 1983 — Class Reunion</title><style>@page{size:landscape;margin:12mm}body{font-family:Arial;color:#222}h1{font:700 22px Georgia;margin:0 0 5px}p{margin:0 0 14px;color:#666;font-size:12px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #aaa;padding:6px 7px;text-align:left;vertical-align:top}th{font-weight:700}</style></head><body><h1>COEP ENTC 1983 — Class Reunion</h1><p>Class list</p><table><thead><tr><th>S.N.</th><th>Name</th><th>Address</th><th>Town / City</th><th>Phone No.</th><th>Email</th></tr></thead><tbody>'+rows+'</tbody></table></body></html>');
    w.document.close();
    setTimeout(function(){try{w.focus();w.print();}catch(e){}},500);
  }
  function replacePrintButton(){var b=document.getElementById('v3Print');if(!b||b.dataset.v3FixedPrint)return;if(b.parentNode){var n=b.cloneNode(true);n.dataset.v3FixedPrint='1';b.parentNode.replaceChild(n,b);n.addEventListener('click',printV3);}}

  async function albums(){var r=await sb.from('reunion_photo_albums').select('id,title,description,url,sort_order,is_active').order('sort_order',{ascending:true}).order('id',{ascending:true});if(r.error)throw r.error;return r.data||[];}
  function albumCard(a){return '<article class="v3-album-card"><div class="v3-album-copy"><div class="v3-album-icon" aria-hidden="true">📷</div><div><h3>'+esc(a.title)+'</h3><p>'+esc(a.description||'')+'</p></div></div><a class="btn v3-album-btn" href="'+esc(a.url)+'" target="_blank" rel="noopener noreferrer">'+esc(a.title)+' <span aria-hidden="true">→</span></a></article>';}
  async function photosV3(){var app=document.getElementById('app');if(!app)return;app.innerHTML='<section class="card"><div><h2>Photos</h2><div class="stat">Our reunion photographs and event albums are collected here.</div></div><div id="v3AlbumList" class="v3-album-list"><div class="stat">Loading albums…</div></div></section>';try{var a=await albums();var active=a.filter(function(x){return x.is_active;});document.getElementById('v3AlbumList').innerHTML=active.length?active.map(albumCard).join(''):'<p class="stat">No photo albums have been added yet.</p>';}catch(e){document.getElementById('v3AlbumList').innerHTML='<div class="notice error">Could not load photo albums right now.</div>';}}
  window.photosPage=photosV3;

  function albumForm(a){var e=a||null;return '<div class="v3-album-form"><h3>'+(e?'Edit Photo Album':'Add Photo Album')+'</h3><input type="hidden" id="v3AlbumId" value="'+(e?esc(e.id):'')+'"><div class="v3-form-grid"><div><label>Title</label><input id="v3AlbumTitle" maxlength="120" placeholder="e.g. Karla 2025" value="'+(e?esc(e.title):'')+'"></div><div><label>Album link</label><input id="v3AlbumUrl" type="url" placeholder="https://..." value="'+(e?esc(e.url):'')+'"></div><div class="full"><label>Short description</label><textarea id="v3AlbumDesc" maxlength="500" placeholder="A short description of the event or album">'+(e?esc(e.description||''):'')+'</textarea></div><div><label>Display order</label><input id="v3AlbumOrder" type="number" value="'+(e?Number(e.sort_order||0):0)+'"></div><div class="v3-album-active"><label><input id="v3AlbumActive" type="checkbox" '+(!e||e.is_active?'checked':'')+'> Show this album</label></div></div><div class="actions"><button class="btn" onclick="v3SaveAlbum()">'+(e?'Save Changes':'Add Album')+'</button>'+(e?'<button class="btn secondary" onclick="v3CancelAlbumEdit()">Cancel</button>':'')+'</div></div>';}
  async function albumAdminSection(){var a=await albums();var rows=a.map(function(x){return '<div class="v3-album-admin-row"><div><strong>'+esc(x.title)+'</strong><div class="small">'+esc(x.description||'')+'</div><div class="small">'+esc(x.url)+'</div></div><div class="v3-album-admin-actions"><button class="btn secondary" onclick="v3EditAlbum('+Number(x.id)+')">Edit</button><button class="btn danger" onclick="v3DeleteAlbum('+Number(x.id)+')">Delete</button></div></div>';}).join('');return '<section class="card" id="v3AlbumAdmin"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><h2>Photo Albums</h2><p class="stat">Add and maintain the event album links shown under Photos.</p></div><button class="btn secondary" onclick="v3ShowAlbumForm()">+ Add Album</button></div><div id="v3AlbumFormHost"></div><div id="v3AlbumAdminList" class="v3-album-admin-list">'+(rows||'<p class="small">No albums yet.</p>')+'</div></section>';}
  window.v3ShowAlbumForm=function(a){var h=document.getElementById('v3AlbumFormHost');if(h)h.innerHTML=albumForm(a);document.getElementById('v3AlbumTitle')?.focus();};
  window.v3CancelAlbumEdit=function(){var h=document.getElementById('v3AlbumFormHost');if(h)h.innerHTML='';};
  window.v3EditAlbum=async function(id){try{var a=(await albums()).find(function(x){return Number(x.id)===Number(id);});if(a)v3ShowAlbumForm(a);}catch(e){alert('Could not load the album.');}};
  window.v3SaveAlbum=async function(){var id=document.getElementById('v3AlbumId')?.value||'',title=document.getElementById('v3AlbumTitle')?.value.trim()||'',description=document.getElementById('v3AlbumDesc')?.value.trim()||'',url=document.getElementById('v3AlbumUrl')?.value.trim()||'',sort=Number(document.getElementById('v3AlbumOrder')?.value||0),active=!!document.getElementById('v3AlbumActive')?.checked;if(!title||!url||!/^https:\/\//i.test(url)){alert('Please enter a title and a valid HTTPS album link.');return;}var r=id?await sb.rpc('reunion_photo_album_update',{p_id:Number(id),p_title:title,p_description:description,p_url:url,p_sort_order:sort,p_is_active:active}):await sb.rpc('reunion_photo_album_add',{p_title:title,p_description:description,p_url:url,p_sort_order:sort});if(r.error){alert(r.error.message||'Could not save the album.');return;}await window.adminPage();};
  window.v3DeleteAlbum=async function(id){if(!confirm('Delete this photo album link?'))return;var r=await sb.rpc('reunion_photo_album_delete',{p_id:Number(id)});if(r.error){alert(r.error.message||'Could not delete the album.');return;}await window.adminPage();};
  var baseAdmin=window.adminPage;
  if(typeof baseAdmin==='function'){window.adminPage=async function(){await baseAdmin();replacePrintButton();try{if(!document.getElementById('v3AlbumAdmin')){var app=document.getElementById('app');if(app)app.insertAdjacentHTML('beforeend',await albumAdminSection());}}catch(e){}};}

  function renderV3Login(){var app=document.getElementById('app');if(!app)return;app.innerHTML='<section class="card"><h2>Welcome</h2><p class="stat">Enter the email address registered for your class record and we’ll send you a secure sign-in link.</p><label>Email address</label><input id="email" type="email" placeholder="you@example.com"><div class="actions"><button class="btn" id="v3SendLink">Send sign-in link</button></div><div id="msg"></div><p class="small">On your first visit, you’ll be asked to match yourself to the class list.</p></section>';document.getElementById('v3SendLink').addEventListener('click',v3SendLink);}
  var busy=false,timer=null;
  function cooldown(){var b=document.getElementById('v3SendLink');if(!b)return;busy=true;b.disabled=true;var n=60;b.textContent='Send again in '+n+'s';clearInterval(timer);timer=setInterval(function(){n--;if(n<=0){clearInterval(timer);busy=false;b.disabled=false;b.textContent='Send sign-in link';}else b.textContent='Send again in '+n+'s';},1000);}
  async function v3SendLink(){if(busy)return;var e=(document.getElementById('email')?.value||'').trim().toLowerCase(),m=document.getElementById('msg');if(!e){m.innerHTML='<div class="notice error">Please enter your email.</div>';return;}var b=document.getElementById('v3SendLink');busy=true;b.disabled=true;b.textContent='Sending…';try{var r=await sb.auth.signInWithOtp({email:e,options:{emailRedirectTo:location.origin+'/v3-auth.html',shouldCreateUser:true}});if(r.error){var text=String(r.error.message||'').toLowerCase(),status=Number(r.error.status||r.error.code||0);if(status===429||text.includes('rate')||text.includes('too many')||text.includes('after')||text.includes('security purposes')){cooldown();m.innerHTML='<div class="notice error">Please wait about a minute before requesting another sign-in link. If you already requested one, use the most recent email.</div>';return;}busy=false;b.disabled=false;b.textContent='Send sign-in link';m.innerHTML='<div class="notice error">We could not send the sign-in link right now. Please try again.</div>';return;}m.innerHTML='<div class="notice">Sign-in email sent. Please use the most recent email and check Spam or Promotions if needed.</div>';cooldown();}catch(e){busy=false;b.disabled=false;b.textContent='Send sign-in link';m.innerHTML='<div class="notice error">We could not send the sign-in link right now. Please try again.</div>';}}
  window.sendLink=v3SendLink;
  try{sb.auth.getSession().then(function(r){if(window.parent!==window && !r.data.session){renderV3Login();}});}catch(e){}

  var css=document.createElement('style');css.textContent='.v3-album-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:18px}.v3-album-card{border:1px solid var(--line);border-radius:18px;background:linear-gradient(135deg,#fffdf8,#fff4dc);padding:20px;display:flex;flex-direction:column;justify-content:space-between;gap:18px}.v3-album-copy{display:flex;gap:14px;align-items:flex-start}.v3-album-icon{width:50px;height:50px;border-radius:50%;background:#fff0b0;border:2px solid #f0d86d;display:grid;place-items:center;font-size:24px;flex:none}.v3-album-card h3{font-size:22px;margin:2px 0 6px}.v3-album-card p{margin:0;color:var(--muted);line-height:1.5}.v3-album-btn{align-self:flex-start;text-decoration:none}.v3-album-form{margin-top:18px;padding:18px;border:1px solid var(--line);border-radius:16px;background:#fffaf1}.v3-album-form h3{font-size:20px;margin-bottom:14px}.v3-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.v3-form-grid .full{grid-column:1/-1}.v3-album-active{display:flex;align-items:end}.v3-album-active label{margin:0;text-transform:none;letter-spacing:0}.v3-album-active input{width:auto;margin-right:7px}.v3-album-admin-list{margin-top:16px;display:grid;gap:8px}.v3-album-admin-row{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:12px;border:1px solid var(--line);border-radius:14px;background:#fffaf1}.v3-album-admin-row .small{overflow-wrap:anywhere}.v3-album-admin-actions{display:flex;gap:6px;flex:none}.v3-album-admin-actions .btn{padding:8px 10px;font-size:12px}@media(max-width:700px){.v3-album-list{grid-template-columns:1fr}.v3-form-grid{grid-template-columns:1fr}.v3-form-grid .full{grid-column:auto}.v3-album-admin-row{align-items:flex-start;flex-direction:column}.v3-album-admin-actions{width:100%}.v3-album-admin-actions .btn{flex:1}.v3-album-btn{width:100%;text-align:center}}';document.head.appendChild(css);
  setInterval(replacePrintButton,500);
})();
